apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-pvc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: 'https://github.com/AlexBerry0/k3s-homelab.git'
    targetRevision: HEAD
    path: immich
    directory:
      include: 'pvc.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true