apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/AlexBerry0/k3s-homelab.git'
    targetRevision: HEAD
    path: postgres
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: immich
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: { prune: true, selfHeal: true }