apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/AlexBerry0/k3s-homelab.git'
    targetRevision: HEAD
    path: postgres
    directory:
      include: 'sealed-postgres-secret.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated: { prune: true, selfHeal: true }