immich:
  immich:
    persistence:
      library:
        existingClaim: "immich-library-pvc"

  redis:
    enabled: true

  postgresql:
    enabled: false
    postgresqlHost: "postgres-postgresql"
    postgresqlUsername: "immich"
    postgresqlDatabase: "immich"
    existingSecret: "postgres-postgresql"