immich:
  immich:
    persistence:
      library:
        existingClaim: "immich-library-pvc"
    server:
      env:
        - name: TZ
          value: "Pacific/Auckland"

  redis:
    enabled: true

  postgresql:
    enabled: false
    postgresqlHost: "postgres-postgresql"
    postgresqlUsername: "immich"
    postgresqlDatabase: "immich"
    existingSecret: "postgres-postgresql"