immich:
  immich:
    persistence:
      library:
        existingClaim: "immich-library-pvc"
    server:
      env:
        - name: TZ
          value: "Pacific/Auckland"
      probes:
        startup:
          spec:
            failureThreshold: 360

  redis:
    enabled: true

  postgresql:
    enabled: false
    auth:
      username: "immich"
      database: "immich"
      existingSecret: "postgres-secret"
      secretPasswordKey: "password"
    primary:
      host: "postgres-postgresql"