immich:
  env:
        TZ: "Pacific/Auckland"
        DB_HOSTNAME: "postgres-postgresql"
        DB_USERNAME: "immich"
        DB_DATABASE_NAME: "postgres"
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: "postgres-secret"
              key: "password"
  immich:
    persistence:
      library:
        existingClaim: "immich-library-pvc"
    server:
      probes:
        startup:
          spec:
            failureThreshold: 360
  redis:
    enabled: true