immich:
  immich:
    persistence:
      library:
        existingClaim: "immich-library-pvc"
    server:
      env:
        - name: TZ
          value: "Pacific/Auckland"
      probes:
        startup:
          spec:
            failureThreshold: 360

  redis:
    enabled: true

postgresql:
  enabled: false

postgresqlHost: "postgres-postgresql"
postgresqlUsername: "immich"
postgresqlDatabase: "immich"

existingSecret: "postgres-secret"
secretPasswordKey: "password"
