immich:
  immich:
    persistence:
      library:
        existingClaim: "immich-library-pvc"
    server:
      env:
        - name: TZ
          value: "Pacific/Auckland"
      probes:
        startup:
          spec:
            failureThreshold: 360
    postgresql:
      host: "postgres-postgresql"
      username: "immich"
      database: "immich"

  redis:
    enabled: true

  postgresql:
    auth:
      existingSecret: "postgres-secret"
      secretPasswordKey: "password"