
redis:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 8Gi

controller:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 5Gi

repoServer:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 10Gi